# Generated by Django 5.2.11 on 2026-02-15 04:05

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "actor_uid",
                    models.CharField(
                        blank=True, default="", max_length=26, verbose_name="actor UID"
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="actor label",
                    ),
                ),
                ("action", models.CharField(max_length=128, verbose_name="action")),
                ("resource", models.CharField(max_length=64, verbose_name="resource")),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="resource ID",
                    ),
                ),
                (
                    "resource_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="resource label",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="scope"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="payload"),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="detail"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="request ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                    models.Index(
                        fields=["scope", "timestamp"],
                        name="audit_audit_scope_12aea9_idx",
                    ),
                    models.Index(
                        fields=["scope", "resource", "resource_id"],
                        name="audit_audit_scope_4475d2_idx",
                    ),
                    models.Index(
                        fields=["resource", "resource_id"],
                        name="audit_audit_resourc_3e0c90_idx",
                    ),
                    models.Index(
                        fields=["actor_uid", "timestamp"],
                        name="audit_audit_actor_u_f7c344_idx",
                    ),
                ],
            },
        ),
    ]
