# Generated by Django 5.2.4 on 2025-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "code_salt",
                    models.BinaryField(
                        help_text="Random salt used for hashing the verification code.",
                        verbose_name="code salt",
                    ),
                ),
                (
                    "code_hash",
                    models.BinaryField(
                        help_text="Hashed verification code for secure storage.",
                        verbose_name="code hash",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                ("expire_time", models.DateTimeField(verbose_name="expire time")),
                (
                    "verify_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When this code was successfully verified.",
                        null=True,
                        verbose_name="verify time",
                    ),
                ),
            ],
            options={
                "verbose_name": "email verification",
                "verbose_name_plural": "email verifications",
                "indexes": [
                    models.Index(
                        fields=["email", "expire_time", "verify_time", "create_time"],
                        name="verikit_ema_email_d3478e_idx",
                    ),
                    models.Index(
                        fields=["email", "create_time"],
                        name="verikit_ema_email_f3d3fe_idx",
                    ),
                    models.Index(
                        fields=["create_time"], name="verikit_ema_create__ca3072_idx"
                    ),
                    models.Index(
                        fields=["expire_time"], name="verikit_ema_expire__697b4d_idx"
                    ),
                ],
            },
        ),
    ]
