import secrets
import string
from functools import partial

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.mail import EmailMessage
from django.core.signing import BadSignature, SignatureExpired, Signer, TimestampSigner
from django.db import transaction
from django.db.models import QuerySet
from django.db.models.functions import Now
from django.template.loader import render_to_string
from loguru import logger

from app.infra.models import Mutex
from app.utils.shorthands import sanitize_email_subject
from app.verikit.models import EmailVerification

normalize_email = get_user_model().objects.normalize_email


class EmailVerificationService:
    """Service for handling email verifications."""

    code_length = 6
    code_chars = string.digits
    code_signer = Signer(salt="verikit.email_code")
    token_signer = TimestampSigner(salt="verikit.email_token")

    verification_email_subject = "verikit/verification-email-subject.html"
    verification_email_body = "verikit/verification-email-body.html"

    @classmethod
    def issue_code(cls, email: str) -> EmailVerification | None:
        """Issues a new verification code for the given email address.

        If there is already a verification code created recently, returns ``None``.

        Returns:
            The ``EmailVerification`` object if a code was issued, otherwise ``None``.
        """
        with Mutex.lock_in_transaction(normalize_email(email), namespace=cls.__name__):
            if (
                cls.active_verifications(email)
                .filter(create_time__gte=Now() - settings.VERIKIT_EMAIL_CODE_INTERVAL)
                .exists()
            ):
                return None

            code = cls.generate_code()
            code_hash = cls.sign_code(email, code)
            email_verification = EmailVerification.objects.create(
                email=email,
                code_hash=code_hash,
                expire_time=Now() + settings.VERIKIT_EMAIL_CODE_EXPIRY,
            )
            email_verification.refresh_from_db()
            logger.info("Verification code issued.", email=email)
            transaction.on_commit(partial(cls.send_verification_email, email, code))
            return email_verification

    @classmethod
    def verify_code(cls, email: str, code: str) -> str | None:
        """Verifies the given code for the given email address.

        Upon successful verification, all other active codes for the same email address
        will be invalidated and a signed verification token is returned.

        Returns:
            A signed verification token if the code is valid, otherwise ``None``.
        """
        with Mutex.lock_in_transaction(normalize_email(email), namespace=cls.__name__):
            active_verifications = cls.active_verifications(email)
            if not any(
                cls.check_code(email_verification, code)
                for email_verification in active_verifications
            ):
                return None

            # Invalidate other verifications.
            cls.active_verifications(email).update(verify_time=Now())

            logger.info("Verification code verified.", email=email)
            return cls.issue_token(email)

    @classmethod
    def verify_token(cls, token: str) -> str | None:
        """Verify an email verification token generated by ``issue_token``.

        Returns:
            The normalized email address if the token is valid and within the allowed
            lifetime. Returns ``None`` for expired, tampered, or malformed tokens.
        """

        try:
            email = cls.token_signer.unsign(
                token,
                max_age=settings.VERIKIT_EMAIL_TOKEN_EXPIRY,
            )
        except (SignatureExpired, BadSignature):
            return None

        return normalize_email(email)

    @classmethod
    def active_verifications(cls, email: str) -> QuerySet[EmailVerification]:
        """Return a queryset of active verifications for the given email address.

        Returns:
            A queryset of active ``EmailVerification`` objects.
        """
        return EmailVerification.objects.filter(
            email__iexact=email,
            expire_time__gte=Now(),
            verify_time__isnull=True,
        )

    @classmethod
    def generate_code(cls) -> str:
        """Generates a random verification code."""
        return "".join(secrets.choice(cls.code_chars) for _ in range(cls.code_length))

    @classmethod
    def sign_code(cls, email: str, code: str) -> str:
        """Computes an HMAC for the given email verification code."""
        message = f"{normalize_email(email)}:{code}"
        return cls.code_signer.signature(message)

    @classmethod
    def check_code(cls, email_verification: EmailVerification, code: str) -> bool:
        """Checks the given code against the given email verification object."""
        message = f"{normalize_email(email_verification.email)}:{code}"
        signed = f"{message}{cls.code_signer.sep}{email_verification.code_hash}"
        try:
            cls.code_signer.unsign(signed)
        except BadSignature:
            return False
        return True

    @classmethod
    def send_verification_email(cls, email: str, code: str) -> None:
        """Sends a verification email to the given email address."""
        context = {
            "site_name": settings.SITE_NAME,
            "code": code,
        }
        render = partial(render_to_string, context=context)

        subject: str = render(cls.verification_email_subject)
        subject = sanitize_email_subject(subject)

        body = render(cls.verification_email_body)

        logger.info("Sending verification email.", email=email)
        mail = EmailMessage(subject, body, to=[email])
        mail.send()

    @classmethod
    def issue_token(cls, email: str) -> str:
        """Issue a signed verification token for the given email address."""
        return cls.token_signer.sign(normalize_email(email))
