[project]
name = "conference"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "apscheduler>=3.11.0",
    "django-cleanup>=9.0.0",
    "django-extensions>=4.1",
    "django-ipware>=7.0.1",
    "django-mailer>=2.3.2",
    "django-ninja>=1.4.3",
    "django-stubs-ext~=6.0",
    "django[argon2]~=6.0",
    "httpx>=0.28.1",
    "ipython>=9.4.0",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "magika>=1.0.1",
    "markdown-it-py[linkify]>=4.0.0",
    "nh3>=0.3.2",
    "orjson>=3.11.0",
    "pydantic[email]>=2.11.7",
    "python-decouple>=3.8",
    "python-ulid-django>=1.2.1",
    "python-ulid[pydantic]>=3.0.0",
    "pyyaml>=6.0.2",
    "rapidfuzz>=3.14.3",
    "sentry-sdk>=2.52.0",
    "servestatic[brotli]>=3.1.0",
    "typst>=0.14.8",
]

[dependency-groups]
dev = [
    "hupper>=1.12.1",
    "pyopenssl>=25.1.0",
    "rust-just>=1.42.3",
    "werkzeug>=3.1.5",
]
lint = [
    "django-stubs[compatible-mypy]~=6.0",
    "mypy<2.2",
    "pre-commit>=4.2.0",
    "ruff>=0.12.4",
    "types-jsonschema>=4.25.1.20251009",
]
prod = [
    "granian>=2.7.2",
    "supervisor>=4.3.0 ; sys_platform != 'win32'",
]
test = [
    "faker>=37.4.2",
    "jsonschema>=4.25.1",
    "pypdf>=6.13.3",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "pytest-django>=4.11.1",
    "pytest-env>=1.2.0",
    "pytest-mock>=3.14.1",
    "pytest-randomly>=3.16.0",
    "pytest-xdist>=3.8.0",
    "respx>=0.22.0",
]

[tool.uv]
default-groups = "all"

[tool.ruff]
cache-dir = ".cache/ruff"

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "I", # isort
    "PGH", # pygrep-hooks
    "UP", # pyupgrade
    "S", # flake8-bandit
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "DJ", # flake8-django
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "FURB", # refurb
    "RUF", # Ruff-specific rules
]
ignore = [
    # Suppressed by ruff formatter.
    "W191", # tab-indentation
    "E111", # indentation-with-invalid-multiple
    "E114", # indentation-with-invalid-multiple-comment
    "E117", # over-indented
]

[tool.ruff.lint.per-file-ignores]
"scripts/dev-setup.py" = [
    "S603", # subprocess-without-shell-equals-true
    "S607", # Starting a process with a partial executable path
]
"tests/**/*.py" = [
    "S101", # assert
    "S105", # hardcoded-password-string
]
"**/migrations/*.py" = [
    "E501", # line-too-long
    "RUF001", # ambiguous-unicode-character-string
    "RUF012", # mutable-class-default
]

[tool.mypy]
strict = true
cache_dir = ".cache/mypy"
mypy_path = "etc/stubs"
num_workers = 8
plugins = [
    "mypy_django_plugin.main",
]

[tool.django-stubs]
django_settings_module = "app.settings"

[tool.pytest]
strict = true
cache_dir = ".cache/pytest"
addopts = [
    "--doctest-modules",
    "--import-mode", "importlib",
    "--cov-config", "pyproject.toml",
    "--cov-report", "term:skip-covered",
    "--cov-report", "html",
    "--cov-fail-under", "100",
]
asyncio_mode = "auto"
markers = [
    "expect_audit_error: test intentionally triggers audit error logging",
]
DJANGO_SETTINGS_MODULE = "app.settings"
env = ["SENTRY_DSN="]

[tool.coverage.run]
branch = true
data_file = ".cache/coverage/data.db"
disable_warnings = ["no-data-collected"]
omit = [
    "*/migrations/*",
    "*/wsgi.py",
    "*/asgi.py",
    "app/frontend/templatetags/*",
    "app/patches.py",
]

[tool.coverage.report]
exclude_also = [
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@overload",
    "case _ as unreachable:",
]

[tool.coverage.html]
directory = "var/cov-report"

[tool.markdownlint]
default = true
MD007 = { indent = 4 }
MD013 = { line_length = 88, strict = true }
