EVENT_SCHEDULER_START: int
EVENT_SCHEDULER_STARTED: int
EVENT_SCHEDULER_SHUTDOWN: int
EVENT_SCHEDULER_PAUSED: int
EVENT_SCHEDULER_RESUMED: int
EVENT_EXECUTOR_ADDED: int
EVENT_EXECUTOR_REMOVED: int
EVENT_JOBSTORE_ADDED: int
EVENT_JOBSTORE_REMOVED: int
EVENT_ALL_JOBS_REMOVED: int
EVENT_JOB_ADDED: int
EVENT_JOB_REMOVED: int
EVENT_JOB_MODIFIED: int
EVENT_JOB_EXECUTED: int
EVENT_JOB_ERROR: int
EVENT_JOB_MISSED: int
EVENT_JOB_SUBMITTED: int
EVENT_JOB_MAX_INSTANCES: int
EVENT_ALL: int

class SchedulerEvent: ...
