# Generated by Django 5.2.4 on 2025-08-17 05:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mutex",
            fields=[
                (
                    "key_hash",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="key hash",
                    ),
                ),
                (
                    "touch_time",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="touch time",
                    ),
                ),
            ],
            options={
                "verbose_name": "mutex",
                "verbose_name_plural": "mutexes",
                "indexes": [
                    models.Index(
                        fields=["touch_time"],
                        name="infra_mutex_touch_t_9d324f_idx",
                    )
                ],
            },
        ),
    ]
