# Generated by Django 5.2.4 on 2025-09-04 12:52

import django.db.models.deletion
import ulid
import ulid_django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_passwordresettoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text=(
                            "Unique identifier for the conference (e.g., 'CBPK-2020')."
                        ),
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Full title of the conference.",
                        max_length=255,
                        verbose_name="display name",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Designates whether this conference is active. "
                            "Unselect this instead of deleting the conference."
                        ),
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "conference",
                "verbose_name_plural": "conferences",
            },
        ),
        migrations.CreateModel(
            name="ConferenceRole",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "Unique identifier for the role "
                            "(e.g., 'admin', 'user', 'viewer')."
                        ),
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for the role.",
                        max_length=255,
                        unique=True,
                        verbose_name="display name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the role.",
                        verbose_name="description",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions granted to users with this role.",
                        to="core.permission",
                        verbose_name="permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "conference role",
                "verbose_name_plural": "conference roles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name of the track.",
                        max_length=255,
                        verbose_name="display name",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Designates whether this track is active. "
                            "Unselect this instead of deleting the track."
                        ),
                        verbose_name="active",
                    ),
                ),
                (
                    "ordering",
                    models.IntegerField(
                        default=0,
                        help_text="Determines the display order of tracks.",
                        verbose_name="ordering",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        related_query_name="track",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "track",
                "verbose_name_plural": "tracks",
                "ordering": ("conference", "ordering", "display_name"),
            },
        ),
        migrations.CreateModel(
            name="TrackRole",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "Unique identifier for the role "
                            "(e.g., 'admin', 'user', 'viewer')."
                        ),
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for the role.",
                        max_length=255,
                        unique=True,
                        verbose_name="display name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the role.",
                        verbose_name="description",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions granted to users with this role.",
                        to="core.permission",
                        verbose_name="permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "track role",
                "verbose_name_plural": "track roles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConferenceRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        related_query_name="role_assignment",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        related_query_name="assignment",
                        to="conference.conferencerole",
                        verbose_name="role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "conference role assignment",
                "verbose_name_plural": "conference role assignments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conference", "user", "role"),
                        name="unique_conference_user_role",
                        violation_error_code="unique",
                        violation_error_message=(
                            "The conference role assignment already exists."
                        ),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        related_query_name="assignment",
                        to="conference.trackrole",
                        verbose_name="role",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        related_query_name="role_assignment",
                        to="conference.track",
                        verbose_name="track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "track role assignment",
                "verbose_name_plural": "track role assignments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("track", "user", "role"),
                        name="unique_track_user_role",
                        violation_error_code="unique",
                        violation_error_message=(
                            "The track role assignment already exists."
                        ),
                    )
                ],
            },
        ),
    ]
