# Generated by Django 5.2.8 on 2025-11-14 01:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conference", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencerole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions granted to users with this role.",
                to="core.permission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="conferenceroleassignment",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                related_query_name="role_assignment",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="conferenceroleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                related_query_name="assignment",
                to="conference.conferencerole",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="conferenceroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                related_query_name="invitation",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="conference_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="invitations",
                related_query_name="invitation",
                to="conference.conferencerole",
                verbose_name="conference roles",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitee_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Set when the invitation is accepted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_invitations",
                related_query_name="received_invitation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="invitee user",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                related_query_name="sent_invitation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="inviter",
            ),
        ),
        migrations.AddField(
            model_name="invitationtrackentry",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_entries",
                related_query_name="track_entry",
                to="conference.invitation",
                verbose_name="invitation",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="interested_keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords the user is interested in for paper assignment.",
                related_name="+",
                to="conference.keyword",
                verbose_name="interested keywords",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Keywords applicable to this conference. "
                    "This is only used to display options on the frontend "
                    "and will not be enforced."
                ),
                to="conference.keyword",
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="keywordset",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, to="conference.keyword", verbose_name="keyword set"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                related_query_name="track",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="invitationtrackentry",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="conference.track",
                verbose_name="track",
            ),
        ),
        migrations.AddField(
            model_name="trackrole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions granted to users with this role.",
                to="core.permission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="invitationtrackentry",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="conference.trackrole",
                verbose_name="roles",
            ),
        ),
        migrations.AddField(
            model_name="trackroleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                related_query_name="assignment",
                to="conference.trackrole",
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="trackroleassignment",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                related_query_name="role_assignment",
                to="conference.track",
                verbose_name="track",
            ),
        ),
        migrations.AddField(
            model_name="trackroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="userconferenceprofile",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                related_query_name="user_profile",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="userconferenceprofile",
            name="interested_keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords the user is interested in for paper assignment.",
                related_name="+",
                to="conference.keyword",
                verbose_name="interested keywords",
            ),
        ),
        migrations.AddField(
            model_name="userconferenceprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_profiles",
                related_query_name="conference_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceroleassignment",
            index=models.Index(
                fields=["user", "role"], name="conference__user_id_9e5c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceroleassignment",
            index=models.Index(fields=["role"], name="conference__role_id_8e7cb6_idx"),
        ),
        migrations.AddConstraint(
            model_name="conferenceroleassignment",
            constraint=models.UniqueConstraint(
                fields=("conference", "user", "role"),
                name="unique_conference_user_role",
                violation_error_code="unique",
                violation_error_message=(
                    "The conference role assignment already exists."
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["conference", "accept_time", "reject_time"],
                name="conference__confere_740cfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["invitee_email"], name="conference__invitee_c3e7c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                models.F("conference"),
                django.db.models.functions.text.Lower("invitee_email"),
                condition=models.Q(("accept_time__isnull", True)),
                name="unique_pending_conference_invitation",
                violation_error_code="unique",
                violation_error_message=(
                    "A pending invitation already exists for this conference and email."
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["active", "visibility", "create_time"],
                name="conference__active_1c56c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["create_time"], name="conference__create__72209a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=[
                    "conference",
                    "active",
                    "visibility",
                    "ordering",
                    "display_name",
                ],
                name="conference__confere_b946d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["conference", "ordering", "display_name"],
                name="conference__confere_e2fd06_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationtrackentry",
            constraint=models.UniqueConstraint(
                fields=("invitation", "track"),
                name="unique_invitation_track",
                violation_error_code="unique",
                violation_error_message=(
                    "A track entry already exists for this invitation and track."
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="trackroleassignment",
            index=models.Index(
                fields=["user", "role"], name="conference__user_id_bf3fcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackroleassignment",
            index=models.Index(fields=["role"], name="conference__role_id_b5ff9b_idx"),
        ),
        migrations.AddConstraint(
            model_name="trackroleassignment",
            constraint=models.UniqueConstraint(
                fields=("track", "user", "role"),
                name="unique_track_user_role",
                violation_error_code="unique",
                violation_error_message="The track role assignment already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="userconferenceprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "conference"),
                name="unique_user_conference_profile",
                violation_error_code="unique",
                violation_error_message="The user conference profile already exists.",
            ),
        ),
    ]
