# Generated by Django 5.2.11 on 2026-02-21 10:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admincomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The admin who wrote this comment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_comments",
                related_query_name="admin_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="codepool",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_pools",
                related_query_name="code_pool",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="attendancetype",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_types",
                related_query_name="attendance_type",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="conferencefile",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                related_query_name="file",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="conferenceroleassignment",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                related_query_name="role_assignment",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="conferenceroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_role_assignments",
                related_query_name="conference_role_assignment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="ieeeecopyrightconfig",
            name="conference",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ieee_ecopyright_config",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                related_query_name="invitation",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitee_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Set when the invitation is accepted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_invitations",
                related_query_name="received_invitation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="invitee user",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                related_query_name="sent_invitation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="inviter",
            ),
        ),
        migrations.AddField(
            model_name="invitationconferenceroleentry",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_role_entries",
                related_query_name="conference_role_entry",
                to="conference.invitation",
                verbose_name="invitation",
            ),
        ),
        migrations.AddField(
            model_name="invitationtrackroleentry",
            name="invitation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_role_entries",
                related_query_name="track_role_entry",
                to="conference.invitation",
                verbose_name="invitation",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="interested_keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords the user is interested in for paper assignment.",
                related_name="+",
                to="conference.keyword",
                verbose_name="interested keywords",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords applicable to this conference. This is only used to display options on the frontend and will not be enforced.",
                to="conference.keyword",
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="keywordset",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, to="conference.keyword", verbose_name="keyword set"
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                related_query_name="paper",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="conference.keyword",
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                related_query_name="paper",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="ieeeecopyrightconsent",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ieee_ecopyright_consent",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="admincomment",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_comments",
                related_query_name="admin_comment",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="acceptanceletter",
            name="paper",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acceptance_letter",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="paperauthor",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                related_query_name="author",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="paperdecision",
            name="decider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paper_decisions",
                related_query_name="paper_decision",
                to=settings.AUTH_USER_MODEL,
                verbose_name="decider",
            ),
        ),
        migrations.AddField(
            model_name="paperdecision",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                related_query_name="decision",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="paperfinal",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finals",
                related_query_name="final",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="paperfinal",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_finals",
                related_query_name="uploaded_final",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploader",
            ),
        ),
        migrations.AddField(
            model_name="paperlabel",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                related_query_name="label",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                related_query_name="submission",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_submissions",
                related_query_name="uploaded_submission",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploader",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                related_query_name="payment",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="paymentitem",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="conference.payment",
                verbose_name="payment",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="attendance_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                related_query_name="registration",
                to="conference.attendancetype",
                verbose_name="attendance type",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                related_query_name="registration",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="paper",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                related_query_name="registration",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                related_query_name="registration",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="conference.registration",
                verbose_name="registration",
            ),
        ),
        migrations.AddField(
            model_name="paymentitem",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_items",
                related_query_name="payment_item",
                to="conference.registration",
                verbose_name="registration",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="assigner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The admin who assigned this review.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reviews",
                related_query_name="assigned_review",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigner",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                related_query_name="review",
                to="conference.paper",
                verbose_name="paper",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user assigned to review this paper. Null for offline reviews.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                related_query_name="review",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewer",
            ),
        ),
        migrations.AddField(
            model_name="reviewernotificationlog",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_notification_logs",
                related_query_name="reviewer_notification_log",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="reviewernotificationlog",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_notification_logs",
                related_query_name="reviewer_notification_log",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewer",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="code_pool",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracks",
                related_query_name="track",
                to="conference.codepool",
                verbose_name="code pool",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                related_query_name="track",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                related_query_name="paper",
                to="conference.track",
                verbose_name="track",
            ),
        ),
        migrations.AddField(
            model_name="invitationtrackroleentry",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="conference.track",
                verbose_name="track",
            ),
        ),
        migrations.AddField(
            model_name="ieeeecopyrightconfig",
            name="exempt_tracks",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="conference.track",
                verbose_name="exempt tracks",
            ),
        ),
        migrations.AddField(
            model_name="trackroleassignment",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                related_query_name="role_assignment",
                to="conference.track",
                verbose_name="track",
            ),
        ),
        migrations.AddField(
            model_name="trackroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_role_assignments",
                related_query_name="track_role_assignment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="userconferenceprofile",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                related_query_name="user_profile",
                to="conference.conference",
                verbose_name="conference",
            ),
        ),
        migrations.AddField(
            model_name="userconferenceprofile",
            name="interested_keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords the user is interested in for paper assignment.",
                related_name="+",
                to="conference.keyword",
                verbose_name="interested keywords",
            ),
        ),
        migrations.AddField(
            model_name="userconferenceprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_profiles",
                related_query_name="conference_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddConstraint(
            model_name="codepool",
            constraint=models.UniqueConstraint(
                fields=("conference", "prefix"),
                name="unique_pool_prefix",
                violation_error_code="unique",
                violation_error_message="A code pool with this prefix already exists for this conference.",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancetype",
            constraint=models.UniqueConstraint(
                fields=("conference", "display_name"),
                name="unique_attendance_type_display_name",
                violation_error_code="unique",
                violation_error_message="An attendance type with this name already exists for this conference.",
            ),
        ),
        migrations.AddConstraint(
            model_name="conferencefile",
            constraint=models.UniqueConstraint(
                fields=("conference", "name"),
                name="unique_conference_file_name",
                violation_error_code="unique",
                violation_error_message="A file with this name already exists.",
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceroleassignment",
            index=models.Index(
                fields=["user", "role"], name="conference__user_id_e3a0cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceroleassignment",
            index=models.Index(fields=["role"], name="conference__role_e4f6c7_idx"),
        ),
        migrations.AddConstraint(
            model_name="conferenceroleassignment",
            constraint=models.UniqueConstraint(
                fields=("conference", "user", "role"),
                name="unique_conference_role_assignment",
                violation_error_code="unique",
                violation_error_message="The conference role assignment already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="conferenceroleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["Chair", "Secretary", "Reviewer", "Member"])
                ),
                name="conference_role_assignment_role_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationconferenceroleentry",
            constraint=models.UniqueConstraint(
                fields=("invitation", "role"),
                name="unique_invitation_conference_role",
                violation_error_code="unique",
                violation_error_message="A conference role entry already exists for this invitation and role.",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationconferenceroleentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["Chair", "Secretary", "Reviewer", "Member"])
                ),
                name="invitation_conference_role_entry_role_value",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["conference", "accept_time", "reject_time"],
                name="conference__confere_740cfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["invitee_email"], name="conference__invitee_c3e7c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                models.F("conference"),
                django.db.models.functions.text.Lower("invitee_email"),
                condition=models.Q(("accept_time__isnull", True)),
                name="unique_pending_conference_invitation",
                violation_error_code="unique",
                violation_error_message="A pending invitation already exists for this conference and email.",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invitee_user__isnull", True),
                    ("accept_time__isnull", False),
                    _connector="OR",
                ),
                name="invitation_invitee_user_requires_accept_time",
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["active", "visibility", "create_time"],
                name="conference__active_1c56c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["create_time"], name="conference__create__72209a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="valid_date_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="paperauthor",
            constraint=models.UniqueConstraint(
                fields=("paper", "ordering"), name="unique_paper_author_ordering"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperfinal",
            constraint=models.UniqueConstraint(
                fields=("paper", "revision"), name="unique_paper_final_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="paperlabel",
            index=models.Index(
                fields=["key", "value"], name="conference__key_d6bda1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperlabel",
            constraint=models.UniqueConstraint(
                fields=("paper", "key"),
                name="unique_paper_label_key",
                violation_error_code="unique",
                violation_error_message="A label with this key already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="papersubmission",
            constraint=models.UniqueConstraint(
                fields=("paper", "revision"), name="unique_paper_submission_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["conference", "delete_time"],
                name="conference__confere_ad7ae7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("conference", "reference"),
                name="unique_payment_reference",
                violation_error_code="unique",
                violation_error_message="A payment with this reference already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="payment_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("conference", "reference_code"),
                name="unique_reference_code",
                violation_error_code="unique",
                violation_error_message="A registration with this reference code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="payment_item_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reviewer__isnull", False),
                    ("state__in", ["Pending", "Accepted", "Submitted"]),
                ),
                fields=("paper", "reviewer"),
                name="unique_active_review",
                violation_error_code="unique",
                violation_error_message="An active review for this paper and reviewer already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reviewer__isnull", True),
                    models.Q(("offline_reviewer_name", ""), _negated=True),
                ),
                fields=("paper", "offline_reviewer_name"),
                name="unique_offline_review",
                violation_error_code="unique",
                violation_error_message="An offline review for this paper and reviewer already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("originality__isnull", True),
                    models.Q(("originality__gte", 1), ("originality__lte", 5)),
                    _connector="OR",
                ),
                name="review_originality_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("significance__isnull", True),
                    models.Q(("significance__gte", 1), ("significance__lte", 5)),
                    _connector="OR",
                ),
                name="review_significance_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("technical__isnull", True),
                    models.Q(("technical__gte", 1), ("technical__lte", 5)),
                    _connector="OR",
                ),
                name="review_technical_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reference__isnull", True),
                    models.Q(("reference__gte", 1), ("reference__lte", 5)),
                    _connector="OR",
                ),
                name="review_reference_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("presentation__isnull", True),
                    models.Q(("presentation__gte", 1), ("presentation__lte", 5)),
                    _connector="OR",
                ),
                name="review_presentation_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("match_topic__isnull", True),
                    models.Q(("match_topic__gte", 1), ("match_topic__lte", 5)),
                    _connector="OR",
                ),
                name="review_match_topic_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recommendation__isnull", True),
                    models.Q(("recommendation__gte", 1), ("recommendation__lte", 5)),
                    _connector="OR",
                ),
                name="review_recommendation_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewernotificationlog",
            constraint=models.UniqueConstraint(
                fields=("conference", "reviewer"),
                name="unique_reviewer_notification_log",
                violation_error_code="unique",
                violation_error_message="A notification log for this conference and reviewer already exists.",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=[
                    "conference",
                    "active",
                    "visibility",
                    "ordering",
                    "display_name",
                ],
                name="conference__confere_b946d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["conference", "ordering", "display_name"],
                name="conference__confere_e2fd06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                condition=models.Q(("delete_time__isnull", True)),
                fields=["conference", "state"],
                name="conference_paper_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="paper",
            constraint=models.UniqueConstraint(
                fields=("conference", "code"),
                name="unique_conference_code",
                violation_error_code="unique",
                violation_error_message="A paper with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="paper",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("announce_time__isnull", True),
                    (
                        "state__in",
                        ["Rejected", "Accepted", "Accepted (Revision Needed)"],
                    ),
                    _connector="OR",
                ),
                name="announce_time_requires_decided_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationtrackroleentry",
            constraint=models.UniqueConstraint(
                fields=("invitation", "track", "role"),
                name="unique_invitation_track_role",
                violation_error_code="unique",
                violation_error_message="A track role entry already exists for this invitation, track and role.",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitationtrackroleentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["Chair", "Secretary", "Reviewer", "Member"])
                ),
                name="invitation_track_role_entry_role_value",
            ),
        ),
        migrations.AddIndex(
            model_name="trackroleassignment",
            index=models.Index(
                fields=["user", "role"], name="conference__user_id_192cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackroleassignment",
            index=models.Index(fields=["role"], name="conference__role_f9c35f_idx"),
        ),
        migrations.AddConstraint(
            model_name="trackroleassignment",
            constraint=models.UniqueConstraint(
                fields=("track", "user", "role"),
                name="unique_track_role_assignment",
                violation_error_code="unique",
                violation_error_message="The track role assignment already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackroleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["Chair", "Secretary", "Reviewer", "Member"])
                ),
                name="track_role_assignment_role_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="userconferenceprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "conference"),
                name="unique_user_conference_profile",
                violation_error_code="unique",
                violation_error_message="The user conference profile already exists.",
            ),
        ),
    ]
