# Generated by Django 5.2.9 on 2025-12-17 08:55

import django.db.models.deletion
import ulid
import ulid_django.models
from django.conf import settings
from django.db import migrations, models

import app.conference.models.paper


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                ("code", models.SlugField(max_length=128, verbose_name="code")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Under Review", "Under Review"),
                            ("Rejected", "Rejected"),
                            ("Accepted", "Accepted"),
                            (
                                "Accepted (Revision Needed)",
                                "Accepted (Revision Needed)",
                            ),
                        ],
                        default="Draft",
                        max_length=128,
                        verbose_name="state",
                    ),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "Soft delete timestamp. Deleted papers are excluded from "
                            "all normal queries and statistics. Distinct from "
                            "withdrawal."
                        ),
                        null=True,
                        verbose_name="delete time",
                    ),
                ),
                (
                    "withdraw_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "Withdrawal timestamp. If set, the paper is considered "
                            "withdrawn regardless of state. Withdrawn papers remain "
                            "visible in statistics."
                        ),
                        null=True,
                        verbose_name="withdraw time",
                    ),
                ),
                (
                    "announce_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "When the decision was announced to the author. Authors "
                            "only see their paper's decision state after this is set."
                        ),
                        null=True,
                        verbose_name="announce time",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the paper was submitted for review.",
                        null=True,
                        verbose_name="submit time",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="title")),
                (
                    "abstract",
                    models.TextField(blank=True, default="", verbose_name="abstract"),
                ),
                (
                    "contribution",
                    models.TextField(
                        blank=True, default="", verbose_name="contribution"
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        related_query_name="paper",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="conference.keyword",
                        verbose_name="keywords",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        related_query_name="paper",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("conference", models.F("conference"))
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        related_query_name="paper",
                        to="conference.track",
                        verbose_name="track",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper",
                "verbose_name_plural": "papers",
            },
        ),
        migrations.CreateModel(
            name="PaperAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="given name",
                    ),
                ),
                (
                    "family_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="family name",
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Institution or organization with which the individual is "
                            "associated (e.g., 'Department of Physics, University of "
                            "Oxford')."
                        ),
                        max_length=250,
                        verbose_name="affiliation",
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "(Empty)"),
                            ("AF", "AF - Afghanistan"),
                            ("AX", "AX - Åland Islands"),
                            ("AL", "AL - Albania"),
                            ("DZ", "DZ - Algeria"),
                            ("AS", "AS - American Samoa"),
                            ("AD", "AD - Andorra"),
                            ("AO", "AO - Angola"),
                            ("AI", "AI - Anguilla"),
                            ("AQ", "AQ - Antarctica"),
                            ("AG", "AG - Antigua & Barbuda"),
                            ("AR", "AR - Argentina"),
                            ("AM", "AM - Armenia"),
                            ("AW", "AW - Aruba"),
                            ("AC", "AC - Ascension Island"),
                            ("AU", "AU - Australia"),
                            ("AT", "AT - Austria"),
                            ("AZ", "AZ - Azerbaijan"),
                            ("BS", "BS - Bahamas"),
                            ("BH", "BH - Bahrain"),
                            ("BD", "BD - Bangladesh"),
                            ("BB", "BB - Barbados"),
                            ("BY", "BY - Belarus"),
                            ("BE", "BE - Belgium"),
                            ("BZ", "BZ - Belize"),
                            ("BJ", "BJ - Benin"),
                            ("BM", "BM - Bermuda"),
                            ("BT", "BT - Bhutan"),
                            ("BO", "BO - Bolivia"),
                            ("BA", "BA - Bosnia & Herzegovina"),
                            ("BW", "BW - Botswana"),
                            ("BV", "BV - Bouvet Island"),
                            ("BR", "BR - Brazil"),
                            ("IO", "IO - British Indian Ocean Territory"),
                            ("VG", "VG - British Virgin Islands"),
                            ("BN", "BN - Brunei"),
                            ("BG", "BG - Bulgaria"),
                            ("BF", "BF - Burkina Faso"),
                            ("BI", "BI - Burundi"),
                            ("KH", "KH - Cambodia"),
                            ("CM", "CM - Cameroon"),
                            ("CA", "CA - Canada"),
                            ("IC", "IC - Canary Islands"),
                            ("CV", "CV - Cape Verde"),
                            ("BQ", "BQ - Caribbean Netherlands"),
                            ("KY", "KY - Cayman Islands"),
                            ("CF", "CF - Central African Republic"),
                            ("EA", "EA - Ceuta & Melilla"),
                            ("TD", "TD - Chad"),
                            ("CL", "CL - Chile"),
                            ("CN", "CN - China"),
                            ("CX", "CX - Christmas Island"),
                            ("CP", "CP - Clipperton Island"),
                            ("CC", "CC - Cocos (Keeling) Islands"),
                            ("CO", "CO - Colombia"),
                            ("KM", "KM - Comoros"),
                            ("CG", "CG - Congo - Brazzaville"),
                            ("CD", "CD - Congo - Kinshasa"),
                            ("CK", "CK - Cook Islands"),
                            ("CR", "CR - Costa Rica"),
                            ("CI", "CI - Côte d’Ivoire"),  # noqa: RUF001
                            ("HR", "HR - Croatia"),
                            ("CU", "CU - Cuba"),
                            ("CW", "CW - Curaçao"),
                            ("CY", "CY - Cyprus"),
                            ("CZ", "CZ - Czech Republic"),
                            ("DK", "DK - Denmark"),
                            ("DG", "DG - Diego Garcia"),
                            ("DJ", "DJ - Djibouti"),
                            ("DM", "DM - Dominica"),
                            ("DO", "DO - Dominican Republic"),
                            ("EC", "EC - Ecuador"),
                            ("EG", "EG - Egypt"),
                            ("SV", "SV - El Salvador"),
                            ("GQ", "GQ - Equatorial Guinea"),
                            ("ER", "ER - Eritrea"),
                            ("EE", "EE - Estonia"),
                            ("SZ", "SZ - Eswatini"),
                            ("ET", "ET - Ethiopia"),
                            ("FK", "FK - Falkland Islands (Islas Malvinas)"),
                            ("FO", "FO - Faroe Islands"),
                            ("FJ", "FJ - Fiji"),
                            ("FI", "FI - Finland"),
                            ("FR", "FR - France"),
                            ("GF", "GF - French Guiana"),
                            ("PF", "PF - French Polynesia"),
                            ("TF", "TF - French Southern Territories"),
                            ("GA", "GA - Gabon"),
                            ("GM", "GM - Gambia"),
                            ("GE", "GE - Georgia"),
                            ("DE", "DE - Germany"),
                            ("GH", "GH - Ghana"),
                            ("GI", "GI - Gibraltar"),
                            ("GR", "GR - Greece"),
                            ("GL", "GL - Greenland"),
                            ("GD", "GD - Grenada"),
                            ("GP", "GP - Guadeloupe"),
                            ("GU", "GU - Guam"),
                            ("GT", "GT - Guatemala"),
                            ("GG", "GG - Guernsey"),
                            ("GN", "GN - Guinea"),
                            ("GW", "GW - Guinea-Bissau"),
                            ("GY", "GY - Guyana"),
                            ("HT", "HT - Haiti"),
                            ("HM", "HM - Heard & McDonald Islands"),
                            ("HN", "HN - Honduras"),
                            ("HK", "HK - Hong Kong SAR"),
                            ("HU", "HU - Hungary"),
                            ("IS", "IS - Iceland"),
                            ("IN", "IN - India"),
                            ("ID", "ID - Indonesia"),
                            ("IR", "IR - Iran"),
                            ("IQ", "IQ - Iraq"),
                            ("IE", "IE - Ireland"),
                            ("IM", "IM - Isle of Man"),
                            ("IL", "IL - Israel"),
                            ("IT", "IT - Italy"),
                            ("JM", "JM - Jamaica"),
                            ("JP", "JP - Japan"),
                            ("JE", "JE - Jersey"),
                            ("JO", "JO - Jordan"),
                            ("KZ", "KZ - Kazakhstan"),
                            ("KE", "KE - Kenya"),
                            ("KI", "KI - Kiribati"),
                            ("XK", "XK - Kosovo"),
                            ("KW", "KW - Kuwait"),
                            ("KG", "KG - Kyrgyzstan"),
                            ("LA", "LA - Laos"),
                            ("LV", "LV - Latvia"),
                            ("LB", "LB - Lebanon"),
                            ("LS", "LS - Lesotho"),
                            ("LR", "LR - Liberia"),
                            ("LY", "LY - Libya"),
                            ("LI", "LI - Liechtenstein"),
                            ("LT", "LT - Lithuania"),
                            ("LU", "LU - Luxembourg"),
                            ("MO", "MO - Macau SAR"),
                            ("MG", "MG - Madagascar"),
                            ("MW", "MW - Malawi"),
                            ("MY", "MY - Malaysia"),
                            ("MV", "MV - Maldives"),
                            ("ML", "ML - Mali"),
                            ("MT", "MT - Malta"),
                            ("MH", "MH - Marshall Islands"),
                            ("MQ", "MQ - Martinique"),
                            ("MR", "MR - Mauritania"),
                            ("MU", "MU - Mauritius"),
                            ("YT", "YT - Mayotte"),
                            ("MX", "MX - Mexico"),
                            ("FM", "FM - Micronesia"),
                            ("MD", "MD - Moldova"),
                            ("MC", "MC - Monaco"),
                            ("MN", "MN - Mongolia"),
                            ("ME", "ME - Montenegro"),
                            ("MS", "MS - Montserrat"),
                            ("MA", "MA - Morocco"),
                            ("MZ", "MZ - Mozambique"),
                            ("MM", "MM - Myanmar (Burma)"),
                            ("NA", "NA - Namibia"),
                            ("NR", "NR - Nauru"),
                            ("NP", "NP - Nepal"),
                            ("NL", "NL - Netherlands"),
                            ("NC", "NC - New Caledonia"),
                            ("NZ", "NZ - New Zealand"),
                            ("NI", "NI - Nicaragua"),
                            ("NE", "NE - Niger"),
                            ("NG", "NG - Nigeria"),
                            ("NU", "NU - Niue"),
                            ("NF", "NF - Norfolk Island"),
                            ("KP", "KP - North Korea"),
                            ("MK", "MK - North Macedonia"),
                            ("MP", "MP - Northern Mariana Islands"),
                            ("NO", "NO - Norway"),
                            ("OM", "OM - Oman"),
                            ("PK", "PK - Pakistan"),
                            ("PW", "PW - Palau"),
                            ("PS", "PS - Palestine"),
                            ("PA", "PA - Panama"),
                            ("PG", "PG - Papua New Guinea"),
                            ("PY", "PY - Paraguay"),
                            ("PE", "PE - Peru"),
                            ("PH", "PH - Philippines"),
                            ("PN", "PN - Pitcairn Islands"),
                            ("PL", "PL - Poland"),
                            ("PT", "PT - Portugal"),
                            ("PR", "PR - Puerto Rico"),
                            ("QA", "QA - Qatar"),
                            ("RE", "RE - Réunion"),
                            ("RO", "RO - Romania"),
                            ("RU", "RU - Russia"),
                            ("RW", "RW - Rwanda"),
                            ("WS", "WS - Samoa"),
                            ("SM", "SM - San Marino"),
                            ("ST", "ST - São Tomé & Príncipe"),
                            ("CQ", "CQ - Sark"),
                            ("SA", "SA - Saudi Arabia"),
                            ("SN", "SN - Senegal"),
                            ("RS", "RS - Serbia"),
                            ("SC", "SC - Seychelles"),
                            ("SL", "SL - Sierra Leone"),
                            ("SG", "SG - Singapore"),
                            ("SX", "SX - Sint Maarten"),
                            ("SK", "SK - Slovakia"),
                            ("SI", "SI - Slovenia"),
                            ("SB", "SB - Solomon Islands"),
                            ("SO", "SO - Somalia"),
                            ("ZA", "ZA - South Africa"),
                            ("GS", "GS - South Georgia & South Sandwich Islands"),
                            ("KR", "KR - South Korea"),
                            ("SS", "SS - South Sudan"),
                            ("ES", "ES - Spain"),
                            ("LK", "LK - Sri Lanka"),
                            ("BL", "BL - St. Barthélemy"),
                            ("SH", "SH - St. Helena"),
                            ("KN", "KN - St. Kitts & Nevis"),
                            ("LC", "LC - St. Lucia"),
                            ("MF", "MF - St. Martin"),
                            ("PM", "PM - St. Pierre & Miquelon"),
                            ("VC", "VC - St. Vincent & Grenadines"),
                            ("SD", "SD - Sudan"),
                            ("SR", "SR - Suriname"),
                            ("SJ", "SJ - Svalbard & Jan Mayen"),
                            ("SE", "SE - Sweden"),
                            ("CH", "CH - Switzerland"),
                            ("SY", "SY - Syria"),
                            ("TW", "TW - Taiwan"),
                            ("TJ", "TJ - Tajikistan"),
                            ("TZ", "TZ - Tanzania"),
                            ("TH", "TH - Thailand"),
                            ("TL", "TL - Timor-Leste"),
                            ("TG", "TG - Togo"),
                            ("TK", "TK - Tokelau"),
                            ("TO", "TO - Tonga"),
                            ("TT", "TT - Trinidad & Tobago"),
                            ("TA", "TA - Tristan da Cunha"),
                            ("TN", "TN - Tunisia"),
                            ("TR", "TR - Turkey (Türkiye)"),
                            ("TM", "TM - Turkmenistan"),
                            ("TC", "TC - Turks & Caicos Islands"),
                            ("TV", "TV - Tuvalu"),
                            ("UM", "UM - U.S. Outlying Islands"),
                            ("VI", "VI - U.S. Virgin Islands"),
                            ("UG", "UG - Uganda"),
                            ("UA", "UA - Ukraine"),
                            ("AE", "AE - United Arab Emirates"),
                            ("GB", "GB - United Kingdom"),
                            ("US", "US - United States"),
                            ("UY", "UY - Uruguay"),
                            ("UZ", "UZ - Uzbekistan"),
                            ("VU", "VU - Vanuatu"),
                            ("VA", "VA - Vatican City"),
                            ("VE", "VE - Venezuela"),
                            ("VN", "VN - Vietnam"),
                            ("WF", "WF - Wallis & Futuna"),
                            ("EH", "EH - Western Sahara"),
                            ("YE", "YE - Yemen"),
                            ("ZM", "ZM - Zambia"),
                            ("ZW", "ZW - Zimbabwe"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="region code",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Author ordering. Lower values appear first.",
                        verbose_name="ordering",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="phone number"
                    ),
                ),
                (
                    "corresponding",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Whether this author is a corresponding author. Used for "
                            "academic attribution in proceedings."
                        ),
                        verbose_name="corresponding",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        related_query_name="author",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper author",
                "verbose_name_plural": "paper authors",
                "ordering": ("ordering",),
            },
        ),
        migrations.CreateModel(
            name="PaperDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("acceptance_letter", "Acceptance Letter"),
                            ("other", "Other"),
                        ],
                        max_length=128,
                        verbose_name="type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=app.conference.models.paper.paper_document_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        related_query_name="document",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper document",
                "verbose_name_plural": "paper documents",
            },
        ),
        migrations.CreateModel(
            name="PaperFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, verbose_name="revision"),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to=app.conference.models.paper.paper_final_source_path,
                        verbose_name="source file",
                    ),
                ),
                (
                    "viewable_file",
                    models.FileField(
                        blank=True,
                        upload_to=app.conference.models.paper.paper_final_viewable_path,
                        verbose_name="viewable file",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finals",
                        related_query_name="final",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_finals",
                        related_query_name="uploaded_final",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper final",
                "verbose_name_plural": "paper finals",
                "ordering": ("-revision",),
            },
        ),
        migrations.CreateModel(
            name="PaperSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=0, verbose_name="revision"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=app.conference.models.paper.paper_submission_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        related_query_name="submission",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_submissions",
                        related_query_name="uploaded_submission",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper submission",
                "verbose_name_plural": "paper submissions",
                "ordering": ("-revision",),
            },
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                condition=models.Q(("delete_time__isnull", True)),
                fields=["conference", "state"],
                name="conference_paper_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="paper",
            constraint=models.UniqueConstraint(
                fields=("conference", "code"),
                name="unique_conference_code",
                violation_error_code="unique",
                violation_error_message="A paper with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="paperauthor",
            constraint=models.UniqueConstraint(
                fields=("paper", "ordering"), name="unique_paper_author_ordering"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperfinal",
            constraint=models.UniqueConstraint(
                fields=("paper", "revision"), name="unique_paper_final_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="papersubmission",
            constraint=models.UniqueConstraint(
                fields=("paper", "revision"), name="unique_paper_submission_revision"
            ),
        ),
    ]
