# Generated by Django 5.2.4 on 2025-10-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, unique=True, verbose_name="text"),
                ),
            ],
            options={
                "ordering": ("text",),
                "verbose_name": "keyword",
                "verbose_name_plural": "keywords",
            },
        ),
        migrations.AddField(
            model_name="conference",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Keywords applicable to this conference. "
                    "This is only used to display options on the frontend "
                    "and will not be enforced."
                ),
                to="conference.keyword",
                verbose_name="keywords",
            ),
        ),
        migrations.CreateModel(
            name="KeywordSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True,
                        to="conference.keyword",
                        verbose_name="keyword set",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "verbose_name": "keyword set",
                "verbose_name_plural": "keyword sets",
            },
        ),
    ]
