# Generated by Django 6.0.3 on 2026-03-17 03:38

import django.db.models.deletion
import ulid
import ulid_django.models
from django.db import migrations, models

import app.audit.types
import app.conference.models.document


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to=app.conference.models.document.paper_proof_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=255, verbose_name="recipient name"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="recipient email"),
                ),
                (
                    "confirmed_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed time"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="comment"),
                ),
                (
                    "comment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="comment time"
                    ),
                ),
                (
                    "notification_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="notification time"
                    ),
                ),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper proof",
                "verbose_name_plural": "paper proofs",
            },
            bases=(app.audit.types.Auditable, models.Model),
        ),
    ]
