# Generated by Django 5.2.9 on 2025-12-22 06:34

import django.db.models.deletion
import ulid
import ulid_django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0003_add_paper_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text=(
                            "Feedback displayed anonymously to authors "
                            "alongside reviews."
                        ),
                        verbose_name="content",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The admin who wrote this comment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_comments",
                        related_query_name="admin_comment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_comments",
                        related_query_name="admin_comment",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin comment",
                "verbose_name_plural": "admin comments",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "offline_reviewer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Display name for reviewers imported from external "
                            "sources. Used when reviewer is null."
                        ),
                        max_length=255,
                        verbose_name="offline reviewer name",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Declined", "Declined"),
                            ("Accepted", "Accepted"),
                            ("Submitted", "Submitted"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=32,
                        verbose_name="state",
                    ),
                ),
                (
                    "originality",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="originality",
                    ),
                ),
                (
                    "significance",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="significance",
                    ),
                ),
                (
                    "technical",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="technical",
                    ),
                ),
                (
                    "reference",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="reference",
                    ),
                ),
                (
                    "presentation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="presentation",
                    ),
                ),
                (
                    "match_topic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="match topic",
                    ),
                ),
                (
                    "recommendation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Score from 1 (lowest) to 5 (highest).",
                        null=True,
                        verbose_name="recommendation",
                    ),
                ),
                (
                    "contribution",
                    models.TextField(
                        blank=True, default="", verbose_name="contribution"
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="decision reason"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Suggestions, questions, and feedback for the authors."
                        ),
                        verbose_name="comments",
                    ),
                ),
                (
                    "confidential_remarks",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Comments visible only to editors, not shared with authors."
                        ),
                        verbose_name="confidential remarks",
                    ),
                ),
                (
                    "assignment_level",
                    models.CharField(
                        choices=[("Conference", "Conference"), ("Track", "Track")],
                        default="Conference",
                        help_text=(
                            "Whether assigned by conference or track admin. "
                            "Track admins cannot cancel conference-level assignments."
                        ),
                        max_length=32,
                        verbose_name="assignment level",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the review was submitted.",
                        null=True,
                        verbose_name="submit time",
                    ),
                ),
                (
                    "assigner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The admin who assigned this review.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews",
                        related_query_name="assigned_review",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigner",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        related_query_name="review",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text=(
                            "The user assigned to review this paper. "
                            "Null for offline reviews."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        related_query_name="review",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("reviewer__isnull", False),
                            ("state__in", ["Pending", "Accepted", "Submitted"]),
                        ),
                        fields=("paper", "reviewer"),
                        name="unique_active_review",
                        violation_error_code="unique",
                        violation_error_message=(
                            "An active review for this paper "
                            "and reviewer already exists."
                        ),
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("reviewer__isnull", True),
                            models.Q(("offline_reviewer_name", ""), _negated=True),
                        ),
                        fields=("paper", "offline_reviewer_name"),
                        name="unique_offline_review",
                        violation_error_code="unique",
                        violation_error_message=(
                            "An offline review for this paper and reviewer "
                            "already exists."
                        ),
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("originality__isnull", True),
                            models.Q(("originality__gte", 1), ("originality__lte", 5)),
                            _connector="OR",
                        ),
                        name="review_originality_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("significance__isnull", True),
                            models.Q(
                                ("significance__gte", 1), ("significance__lte", 5)
                            ),
                            _connector="OR",
                        ),
                        name="review_significance_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("technical__isnull", True),
                            models.Q(("technical__gte", 1), ("technical__lte", 5)),
                            _connector="OR",
                        ),
                        name="review_technical_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reference__isnull", True),
                            models.Q(("reference__gte", 1), ("reference__lte", 5)),
                            _connector="OR",
                        ),
                        name="review_reference_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("presentation__isnull", True),
                            models.Q(
                                ("presentation__gte", 1), ("presentation__lte", 5)
                            ),
                            _connector="OR",
                        ),
                        name="review_presentation_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("match_topic__isnull", True),
                            models.Q(("match_topic__gte", 1), ("match_topic__lte", 5)),
                            _connector="OR",
                        ),
                        name="review_match_topic_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recommendation__isnull", True),
                            models.Q(
                                ("recommendation__gte", 1), ("recommendation__lte", 5)
                            ),
                            _connector="OR",
                        ),
                        name="review_recommendation_range",
                    ),
                ],
            },
        ),
    ]
