# Generated by Django 5.2.4 on 2025-11-01 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0003_keyword_conference_keywords_keywordset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConferenceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "desired_paper_count",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of papers the user wants to review.",
                        verbose_name="desired paper count",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        related_query_name="user_profile",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
                (
                    "interested_keywords",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "Keywords the user is interested in for paper assignment."
                        ),
                        related_name="+",
                        to="conference.keyword",
                        verbose_name="interested keywords",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_profiles",
                        related_query_name="conference_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user conference profile",
                "verbose_name_plural": "user conference profiles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "conference"),
                        name="unique_user_conference_profile",
                        violation_error_code="unique",
                        violation_error_message=(
                            "The user conference profile already exists."
                        ),
                    )
                ],
            },
        ),
    ]
