# Generated by Django 6.1 on 2026-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0003_paper_proof"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paperproof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confirmed_time__isnull", True), ("comment", ""), _connector="OR"
                ),
                name="paper_proof_confirmed_excludes_comment",
            ),
        ),
    ]
