# Generated by Django 5.2.9 on 2025-12-27 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0004_add_review_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Rejected", "Rejected"),
                            ("Accepted", "Accepted"),
                            (
                                "Accepted (Revision Needed)",
                                "Accepted (Revision Needed)",
                            ),
                        ],
                        max_length=128,
                        verbose_name="state",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "Internal note for recording decision rationale. "
                            "Not shown to authors."
                        ),
                        verbose_name="note",
                    ),
                ),
                (
                    "decider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_decisions",
                        related_query_name="paper_decision",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decider",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        related_query_name="decision",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper decision",
                "verbose_name_plural": "paper decisions",
                "ordering": ("-create_time",),
            },
        ),
    ]
