# Generated by Django 5.2.9 on 2025-12-27 03:46

import django.db.models.deletion
from django.db import migrations, models

import app.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0005_add_paper_decision_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=317,
                        validators=[app.utils.models.validate_label_key],
                        verbose_name="key",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=63,
                        validators=[app.utils.models.validate_label_value],
                        verbose_name="value",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        related_query_name="label",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper label",
                "verbose_name_plural": "paper labels",
                "indexes": [
                    models.Index(
                        fields=["key", "value"], name="conference__key_d6bda1_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("paper", "key"),
                        name="unique_paper_label_key",
                        violation_error_code="unique",
                        violation_error_message="A label with this key already exists.",
                    )
                ],
            },
        ),
    ]
