# Generated by Django 5.2.8 on 2025-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0005_invitation_invitationtrackentry_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conference",
            name="conference__active_57f6a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="track",
            name="conference__confere_a237f7_idx",
        ),
        migrations.AddField(
            model_name="conference",
            name="visibility",
            field=models.CharField(
                choices=[("Public", "Public"), ("Admin-Only", "Admin-Only")],
                default="Admin-Only",
                max_length=128,
                verbose_name="visibility",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="visibility",
            field=models.CharField(
                choices=[("Public", "Public"), ("Admin-Only", "Admin-Only")],
                default="Admin-Only",
                max_length=128,
                verbose_name="visibility",
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["active", "visibility", "create_time"],
                name="conference__active_1c56c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=[
                    "conference",
                    "active",
                    "visibility",
                    "ordering",
                    "display_name",
                ],
                name="conference__confere_b946d4_idx",
            ),
        ),
    ]
