# Generated by Django 5.2.9 on 2025-12-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0006_add_paper_label_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptanceLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "rendered_html",
                    models.TextField(
                        blank=True, default="", verbose_name="rendered html"
                    ),
                ),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance_letter",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "acceptance letter",
                "verbose_name_plural": "acceptance letters",
            },
        ),
    ]
