# Generated by Django 5.2.9 on 2025-12-30 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0007_add_acceptance_letter_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paper",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("announce_time__isnull", True),
                    (
                        "state__in",
                        ["Rejected", "Accepted", "Accepted (Revision Needed)"],
                    ),
                    _connector="OR",
                ),
                name="announce_time_requires_decided_state",
            ),
        ),
    ]
