# Generated by Django 5.2.9 on 2025-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0008_add_paper_announce_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="final_revision_limit",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text=(
                    "Maximum number of final version uploads allowed for this paper."
                ),
                verbose_name="final revision limit",
            ),
        ),
    ]
