# Generated by Django 5.2.9 on 2026-01-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0009_add_paper_final_revision_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="registration_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether this conference is currently accepting registrations. "
                    "When disabled, no new registrations can be created."
                ),
                verbose_name="registration enabled",
            ),
        ),
    ]
