# Generated by Django 5.2.9 on 2026-01-01 07:10

import django.db.models.deletion
import ulid
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0010_add_conference_registration_toggle"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="display name"),
                ),
                (
                    "ordering",
                    models.IntegerField(
                        default=0,
                        help_text="Determines the display order of attendance types.",
                        verbose_name="ordering",
                    ),
                ),
                (
                    "admin_only",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "If true, this option is hidden from registrants "
                            "and can only be assigned by administrators."
                        ),
                        verbose_name="admin only",
                    ),
                ),
                (
                    "paper_required",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "If true, this option only appears when "
                            "the registrant selects a paper."
                        ),
                        verbose_name="paper required",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_types",
                        related_query_name="attendance_type",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance type",
                "verbose_name_plural": "attendance types",
                "ordering": ("ordering", "display_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conference", "display_name"),
                        name="unique_attendance_type_display_name",
                        violation_error_code="unique",
                        violation_error_message=(
                            "An attendance type with this name already exists "
                            "for this conference."
                        ),
                    )
                ],
            },
        ),
    ]
