# Generated by Django 5.2.9 on 2026-01-05 01:03

import django.db.models.deletion
import ulid
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0012_add_registration_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "CNY - Renminbi"),
                            ("EUR", "EUR - Euro"),
                            ("HKD", "HKD - Hong Kong dollar"),
                            ("JPY", "JPY - Japanese yen"),
                            ("TWD", "TWD - New Taiwan dollar"),
                            ("USD", "USD - United States dollar"),
                        ],
                        max_length=16,
                        verbose_name="currency",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Payment", "Payment"), ("Refund", "Refund")],
                        max_length=64,
                        verbose_name="type",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("Credit Card", "Credit Card"),
                            ("Wire Transfer", "Wire Transfer"),
                        ],
                        max_length=64,
                        verbose_name="method",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "External transaction ID from cashier or payment gateway."
                        ),
                        max_length=255,
                        verbose_name="reference",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="note")),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Set to soft-delete this payment. Null means active.",
                        null=True,
                        verbose_name="delete time",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        related_query_name="payment",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text=(
                            "Portion of the payment allocated to this registration."
                        ),
                        max_digits=12,
                        verbose_name="amount",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="item",
                        to="conference.payment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_items",
                        related_query_name="payment_item",
                        to="conference.registration",
                        verbose_name="registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment item",
                "verbose_name_plural": "payment items",
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["conference", "delete_time"],
                name="conference__confere_ad7ae7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("conference", "reference"),
                name="unique_payment_reference",
                violation_error_code="unique",
                violation_error_message="A payment with this reference already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="payment_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="payment_item_amount_non_negative",
            ),
        ),
    ]
