# Generated by Django 5.2.9 on 2026-01-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0014_add_receipt_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="IEEEeCopyrightConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_title",
                    models.CharField(max_length=255, verbose_name="publication title"),
                ),
                (
                    "article_source",
                    models.CharField(max_length=255, verbose_name="article source"),
                ),
                (
                    "conference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ieee_ecopyright_config",
                        to="conference.conference",
                        verbose_name="conference",
                    ),
                ),
                (
                    "exempt_tracks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="conference.track",
                        verbose_name="exempt tracks",
                    ),
                ),
            ],
            options={
                "verbose_name": "IEEE eCopyright config",
                "verbose_name_plural": "IEEE eCopyright configs",
            },
        ),
        migrations.CreateModel(
            name="IEEEeCopyrightConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="raw response"
                    ),
                ),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ieee_ecopyright_consent",
                        to="conference.paper",
                        verbose_name="paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "IEEE eCopyright consent",
                "verbose_name_plural": "IEEE eCopyright consents",
            },
        ),
    ]
