# Generated by Django 5.2.9 on 2026-01-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0015_add_ieee_ecopyright_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text=(
                    "End date of the conference. "
                    "For display purposes only; not enforced by the system."
                ),
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="location",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Location of the conference (e.g., 'Cagliari, Italy'). "
                    "For display purposes only; not enforced by the system."
                ),
                max_length=200,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text=(
                    "Start date of the conference. "
                    "For display purposes only; not enforced by the system."
                ),
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AddConstraint(
            model_name="conference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="valid_date_range",
            ),
        ),
    ]
