# Generated by Django 5.2.9 on 2026-01-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0016_add_conference_display_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="paper_final_instructions",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Instructions shown above the final (camera-ready) file upload. "
                    "Supports Markdown formatting. For display purposes only."
                ),
                verbose_name="paper final instructions",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="paper_submission_instructions",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Instructions shown above the paper submission file upload. "
                    "Supports Markdown formatting. For display purposes only."
                ),
                verbose_name="paper submission instructions",
            ),
        ),
    ]
