# Generated by Django 5.2.8 on 2025-11-15 08:41

import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import ulid
import ulid_django.models
from django.conf import settings
from django.db import migrations, models

import app.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has all permissions without "
                            "explicitly assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text=(
                            "Required. 150 characters or fewer. Letters, digits "
                            "and @/./+/-/_ only."
                        ),
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates whether the user can log into this admin site."
                        ),
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Designates whether this user should be treated as active. "
                            "Unselect this instead of deleting accounts."
                        ),
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "uid",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        unique=True,
                        verbose_name="UID",
                    ),
                ),
                (
                    "managed",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates whether this user is controlled by the system. "
                            "Managed users cannot modify their username and email."
                        ),
                        verbose_name="managed",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all "
                            "permissions granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", app.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GlobalRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Read All", "Read All")],
                        max_length=255,
                        verbose_name="role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_role_assignments",
                        related_query_name="global_role_assignment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "global role assignment",
                "verbose_name_plural": "global role assignments",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="Hashed password reset token for secure storage.",
                        max_length=64,
                        unique=True,
                        verbose_name="token hash",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                ("expire_time", models.DateTimeField(verbose_name="expire time")),
                (
                    "consume_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When this token was consumed for password reset.",
                        null=True,
                        verbose_name="consume time",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        related_query_name="password_reset_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "password reset token",
                "verbose_name_plural": "password reset tokens",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="unique_non_empty_email",
                violation_error_code="unique",
                violation_error_message="A user with that email already exists.",
            ),
        ),
        migrations.AddIndex(
            model_name="globalroleassignment",
            index=models.Index(fields=["role"], name="core_global_role_876938_idx"),
        ),
        migrations.AddConstraint(
            model_name="globalroleassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "role"),
                name="unique_global_role_assignment",
                violation_error_code="unique",
                violation_error_message="The role assignment already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="globalroleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["Admin", "Read All"])),
                name="global_role_assignment_role_value",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "create_time"], name="core_passwo_user_id_3fb7f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "expire_time", "consume_time", "token_hash"],
                name="core_passwo_user_id_c9d353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["create_time"], name="core_passwo_create__6b6a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["expire_time"], name="core_passwo_expire__b145a8_idx"
            ),
        ),
    ]
