# Generated by Django 6.0.3 on 2026-04-04 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApiKeySession",
        ),
    ]
