# Generated by Django 5.2.4 on 2025-08-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "Unique identifier for the role "
                            "(e.g., 'admin', 'user', 'viewer')."
                        ),
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for the role.",
                        max_length=255,
                        unique=True,
                        verbose_name="display name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the role.",
                        verbose_name="description",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions granted to users with this role.",
                        to="core.permission",
                        verbose_name="permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "abstract": False,
            },
        ),
    ]
