# Generated by Django 5.2.4 on 2025-08-02 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        related_query_name="assignment",
                        to="core.role",
                        verbose_name="role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "role assignment",
                "verbose_name_plural": "role assignments",
                "indexes": [
                    models.Index(fields=["role"], name="core_roleas_role_id_b988eb_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"),
                        name="unique_user_role",
                        violation_error_code="unique",
                        violation_error_message="The role assignment already exists.",
                    )
                ],
            },
        ),
    ]
