# Generated by Django 5.2.4 on 2025-08-13 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_roleassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="Hashed password reset token for secure storage.",
                        max_length=64,
                        unique=True,
                        verbose_name="token hash",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                ("expire_time", models.DateTimeField(verbose_name="expire time")),
                (
                    "consume_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When this token was consumed for password reset.",
                        null=True,
                        verbose_name="consume time",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        related_query_name="password_reset_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "password reset token",
                "verbose_name_plural": "password reset tokens",
                "indexes": [
                    models.Index(
                        fields=["user", "create_time"],
                        name="core_passwo_user_id_3fb7f9_idx",
                    ),
                    models.Index(
                        fields=["user", "expire_time", "consume_time", "token_hash"],
                        name="core_passwo_user_id_c9d353_idx",
                    ),
                    models.Index(
                        fields=["create_time"], name="core_passwo_create__6b6a46_idx"
                    ),
                    models.Index(
                        fields=["expire_time"], name="core_passwo_expire__b145a8_idx"
                    ),
                ],
            },
        ),
    ]
