# Generated by Django 5.2.4 on 2025-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Designates whether this user is controlled by the system. "
                    "Managed users cannot modify their username and email."
                ),
                verbose_name="managed",
            ),
        ),
    ]
